apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Armazenamento para persistir dados no dev
