version: "3.8"

services:
  # PHP com Xdebug para Desenvolvimento
  php:
    build:
      context: .
      dockerfile: ./docker/php/php.dev.Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - XDEBUG_MODE=debug # Ativa o Xdebug no ambiente de desenvolvimento
    networks:
      - laravel-network

  # Nginx Servindo a Aplicação Laravel
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - laravel-network

  # Banco de Dados MySQL com persistência de dados
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  # Vite.js para compilar Assets (caso esteja usando Vite)
  vite:
    image: node:16-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm run dev # Inicia o servidor de desenvolvimento do Vite
    ports:
      - "3000:3000" # Porta para os assets do frontend
    depends_on:
      - php
    networks:
      - laravel-network

# Volumes persistentes
volumes:
  mysql_data:

# Redes
networks:
  laravel-network:
