services:
  # PHP para Produção
  php:
    build:
      context: .
      dockerfile: ./docker/php/php.prod.Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - laravel-network

  # Nginx para Produção
  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - laravel-network

  # Banco de Dados MySQL
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  # Vite para Build de Assets (caso necessário, será executado antes da implantação)
  vite:
    image: node:16-alpine
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm ci && npm run build # Rodar o build dos assets
    depends_on:
      - php
    networks:
      - laravel-network
    environment:
      - NODE_ENV=production

# Volumes persistentes
volumes:
  mysql_data:

# Redes
networks:
  laravel-network:
